### ISSUE TITLE
Login broken

### ISSUE THREAD

**Issue by ebolloff** [ontohub/ontohub-backend#112]
Start the server and try
```
TOKEN=`http POST :3000/users/sign_in user:='{"name": "ada", "password": "changeme"}' | ruby -e 'puts $stdin.read.match(/"token":\s*"([^"]+)"/)[1]'`
```
and
```
http -j :3000/ada "Authorization: Bearer ${TOKEN}"
```
This should respond with `200`, which it does.
```
http -j :3000/ada "Authorization: Bearer ${TOKEN}asdf"
```
This should respond with a login error, but it responds with `200`.
Also, when you try to login with a non-existant user, the user gets a token which isn't allowed:
```
http POST :3000/users/sign_in user:='{"name": "NotAUser", "password": "changeme"}'
```

**Comment by phyrog** [comment]
I'm looking into this now. Will post what I find.

- warden's `authenticate!` is called during signing in, `authenticate` is called when using a token (this one does not throw `:warden`, so authentication will not fail. Not sure yet why this is used.)
