### ISSUE TITLE
Add graphql query for search

### ISSUE THREAD

**Issue by phyrog** [ontohub/ontohub-backend#138]
## Types

```graphql
union SearchResultTarget = Repository | Organization | User

type SearchResultEntry {
  ranking: Float!
  entry: SearchResultTarget!
}

type SearchResultCount {
  # should include all possible values of SearchCategory as keys
  all: Int!
  organizationalUnits: Int!
  repositories: Int!
}

type SearchResult {
  entries: [SearchResultEntry!]!
  count: SearchResultCount!
}

enum SearchCategory {
  all
  organizationalUnits
  repositories
}
```

## Queries

```graphql
search(query: String!, category: SearchCategory!, limit: Int, skip: Int): SearchResult!
```

If we decide not to send the Elasticsearch ranking with each result, we can simplify `SearchResultEntry` to `SearchResultTarget`.

**Comment by phyrog** [comment]
We might also want to create other types like `RankedOrganizationalUnit`, `RankedRepository` and `RankedOMS` that includes the organizational unit/repository/oms and a ranking value, so we can resort the entries on the client side.

**Comment by tillmo** [comment]
could you please explain where the ranking value comes from?

**Comment by phyrog** [comment]
I think elastic search is able to output a ranking value (this is of course only a search ranking, not quality of the repository or something).
