### ISSUE TITLE
Discussion: Use GraphQL API in REST controllers

### ISSUE THREAD

**Issue by phyrog** [ontohub/ontohub-backend#149]
Proposal: Use the GraphQL API in the other REST controllers to provide read/index actions for linked open data compliance.

That would mean that we scrap the complete JSON API and instead for each controller action specify a set of fields we want to return for that route. (Sort of like predefined views on the GraphQL API)

Pros:
- Returned structure of GraphQL and REST API would be the same
- Less maintainence because of less/shared code
- No possibility of inconsistencies among authorization
- Less dependencies (ActiveModelSerializer)

Cons:
- Format won't follow a "standard"
- A bit more work upfront to port the controllers, although not too much

Ping @eugenk, @ebolloff, @tillmo

**Comment by phyrog** [comment]
To give an example, `GET /ada` would return **exactly** the same result as doing e.g. this GraphQL query:

```graphql
organizationalUnit(id: "ada") {
  id
  displayName
  emailHash
  organizations {
    id
    displayName
  }
  repositories {
    id
    displayName
  }
}
```

which would be in this format:

```json
{
  "data": {
    "organizationalUnit": {
      "id": "ada",
      "displayName": "Ada Lovelace",
      "emailHash": "...",
      "organizations": [{
        "id": "seed-user-organization",
        "displayName": "Seed User Organization"
      }, {
        "id": "other-organization",
        "displayName": "Some other Organization"
      }],
      "repositories": [{
        "id": "ada/repo1",
        "displayName": "Repo1"
      }, {
        "id": "ada/repo2",
        "displayName": "Repo2"
      }]
    }
  },
  "errors": [{
    "message": "Some error message"
  }]
}
```

**Comment by tillmo** [comment]
so the only difference to a real REST API would be that the returned JSON is a bit different? This is OK for me, as long as at least the same information is returned.

**Comment by phyrog** [comment]
Jep, that's the only difference
