### ISSUE TITLE
Find a better way to organize GraphQL types

### ISSUE THREAD

**Issue by phyrog** [ontohub/ontohub-backend#150]
Putting all types in the top level `types` directory is/will become quite messy, same goes for mutations.

One way we could improve this is grouping related files in subdirectories while keeping the one-type-per-file rule:

```
types/repositories/repository_type.rb
types/repositories/repository_visibility_enum.rb
...
```

Alternatively we could group related types in one file:

```ruby
# types/repositories.rb
module Types
  module Repositories
    RepositoryType = GraphQL::ObjectType.define do
      ...
    end

    RepositoryVisibilityEnum = GraphQL::EnumType.define do
      ...
    end
    ...
  end
end
```

**Comment by eugenk** [comment]
I vote for option 2, but with `module Repositories` renamed to `module Repository`  and `RepositoryVisibilityEnum` renamed to `VisibilityEnum` because everything is prefixed with `Types::Repository::`.

**Comment by phyrog** [comment]
The downside to this is that we will be having pretty big files. For mutations at least I would go with option 1.

**Comment by eugenk** [comment]
Right, mutations can get quite big. I forgot for a second that they are types, too. And since consistency is key for quick and easy development, we should not alternate between two type organisation models. Maybe subdirectories are the better choice, then.

**Comment by phyrog** [comment]
Actually they are fields, not types, so we could use different organization schemes.

Another thing we could do with mutations is actually defining the fields (instead of just the resolve proc/class) in the mutation files and not in the `Mutation` type. Then we would have the return types and argument types where the code is instead of having them split over two files.

```ruby
# app/graphql/mutations/repository/save_repository_mutation.rb
module Mutations
  module Repository
    SaveRepositoryMutation = GraphQL::Field.define do
      type Types::Repository::RepositoryType
      argument :id, !types.ID, as: :slug
      argument :data, !Types::Repository::RepositoryChangesetType

      resource ->(_root, arguments, _context) { ... }
      resolve ->(repository, arguments, _context) { ... }
    end
  end
end

# app/graphql/types/mutation_type.rb
Types::MutationType = GraphQL::ObjectType.define do
  field :saveRepository, Mutations::Repository::SaveRepositoryMutation
end
```
