### ISSUE TITLE
Set up asynchronous computing

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-backend#167]
Some tasks like sending emails or evaluate an OMS need to be performed asynchronously (in the background) without blocking the HTTP response.

Set up [ActiveJob](http://edgeguides.rubyonrails.org/active_job_basics.html) with the [backend](http://edgeapi.rubyonrails.org/classes/ActiveJob/QueueAdapters.html) "sneakers". This requires RabbitMQ, which we settled upon as our message broker.

Setup devise to [send the user-account-specific emails asynchronously](https://github.com/plataformatec/devise/wiki/How-To:-Send-devise-emails-in-background-(Resque,-Sidekiq-and-Delayed::Job)).

Furthermore, change the wiki [setup page](https://github.com/ontohub/ontohub-backend/wiki/Setting-up-the-development-environment) to reflect the configuration of the overall development setup, especially RabbitMQ (if needed at all).

**Comment by phyrog** [comment]
Btw, there is also [this gem](https://github.com/lgierth/promise.rb), but I'm not sure if it's really useful in a server context (but the graphql gem can automatically resolve these, so there's that).

**Comment by phyrog** [comment]
Semi-relevant question: How will we trigger a search indexing for e.g. creating a repository? Will we integrate the indexing for this into the backend or will we send the separate indexer a message via RabbitMQ as we do for OMS data?

**Comment by eugenk** [comment]
I'm not sure. Does indexing take much time (on a large database)? If so, we should do it asynchronously as we do for OMS data. Otherwise, we can do it synchronously in the backend. We need to use Elasticsearch in the backend anyway, so there are no additional libraries to include.
