### ISSUE TITLE
Extend seeds

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-backend#168]
The seeds don't reflect the state of development. We should add 
* Admin users
* Regular users
* OrganizationMemberships
* RepositoryMemberships
* Git
  * More diverse repository content (maybe with small fixtures of text, image, pdf located at db/seed/fixtures)
  * Branches
  * Tags without annotation
  * Tags with annotation
* SSH keys (fixtures)

**Comment by phyrog** [comment]
While we're at it, let's throw some ssh keys (as fixtures) in there too.
