### ISSUE TITLE
Add API keys

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-backend#181]
In order for Hets to fetch data from private repositories, we should add API keys.

Since Hets only needs to *read* repository data, it suffices to change the `RepositoryPolicy#show?` method to check for the API key.

---

An API key should be handled the same way as a Devise reset password token, such that the key itself is not saved in the database, but rather a digest value.

Devise token generation: [[1]](https://github.com/plataformatec/devise/blob/ee01bac8b0b828b3da0d79c46115ba65c433d6c8/lib/devise/models/recoverable.rb#L87-L94) [[2]](https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/token_generator.rb#L17-L20)
Devise token validation: [[3]](https://github.com/plataformatec/devise/blob/ee01bac8b0b828b3da0d79c46115ba65c433d6c8/lib/devise/models/recoverable.rb#L144-L147) [[4]](https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/token_generator.rb#L10-L12)

**Comment by phyrog** [comment]
What's the flow of data here? Backend sends message with job description + API token to rabbitmq broker, job is distributed to some worker,  worker uses API key to get repository data?

**Comment by eugenk** [comment]
I suggest that the configuration of each hets-rabbitmq-wrapper contains an API key. We generate one with a rake task in the backend.

So the backend sends normal jobs to the hets-rabbitmq-wrapper. The wrapper then requests the OMS file using the API key.


Ontohub Legacy created time-limited access tokens only for a specific repository. This is actually not needed. What we need is Hets to have full read access.

**Comment by phyrog** [comment]
Ah, okay, I thought you suggested for each repository to have a list of API keys that are authorized to read.

But do we really need that kind of access control? Hets instances can't just join the rabbitmq cluster, can they?

**Comment by phyrog** [comment]
Just realized that the API access is independent of rabbitmq, so it makes sense.

**Comment by phyrog** [comment]
We could also use JWT for this

**Comment by phyrog** [comment]
How will Hets get the repository data? By cloning the repository?

**Comment by eugenk** [comment]
By an HTTP call to the REST API.
