### ISSUE TITLE
Wrap intentionally untested code in nocov

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-backend#49]
Wrap intentionally untested code in `# :nocov:` comments to hide them in the coverage report. See https://github.com/colszowka/simplecov#ignoringskipping-code for an example.

**Comment by ebolloff** [comment]
There are two files which don't have 100% `app/controllers/v2/resources_controller/dsl.rb` and `app/controllers/v2/resources_controller.rb`. @eugenk will deal with them later so this ticket can be closed.
