### ISSUE TITLE
i18n default locale fallback

### ISSUE THREAD

**Issue by DerProfessor** [ontohub/ontohub-backend#503]
When installing i18n in the ontohub/hets-agent repository a warning with the following content showed up:
```
HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.

Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.
```
To avoid complications in the future we need to alter this setting in the config/application/production.rb file since this is the only file affected by the changing.

**Comment by eugenk** [comment]
We don't actually use i18n, so I think this should not break anything.
