### ISSUE TITLE
Solve devise/migrate issue

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-backend#67]
```
rails db:drop
rails db:create
rails db:migrate
```
Fails because of the `devise_for` in the routes. Fix it.

**Comment by phyrog** [comment]
Since we only use the `create` action, we might just replace the `devise_for` with
```ruby
post '/users/sign_in', controller: 'v2/users/sessions', action: :create
```

**Comment by eugenk** [comment]
There will be more with User registration and Token invalidation, but I can't think of a reason to drop this "magic" `devise_for` in favour of this more verbose routing.

**Comment by phyrog** [comment]
Hm. It doesn't seem to be as simple. [`devise_for`](https://github.com/plataformatec/devise/blob/eb0540e0288e58ed43de337be808fc09c9180f41/lib/devise/rails/routes.rb#L224) does a lot more than just define the routes.

**Comment by phyrog** [comment]
Related issue: https://github.com/rails/rails/issues/26319
