### ISSUE TITLE
draw diagram with components and tools

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub-backend#82]
we use so many tools (e.g. mirage, ember_json_schema, gitlab_git...) that an overview diagram would be very useful. Standard gems can be omitted, list only the most important gems.

**Comment by eugenk** [comment]
I have done this with https://github.com/ontohub/ontohub-backend/wiki/Architecture-Details/bbdf7c9918601a6ac9e64078274608d1165a89ac

Please comment if some things are still unclear.

**Comment by phyrog** [comment]
Should be sufficiently covered. Closing this.
