### ISSUE TITLE
Git: Mutex git actions

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-backend#85]
We use two different systems to write to git repositories: [git-shell](https://github.com/ontohub/ontohub-git-shell) and [gitlab-git](https://github.com/ontohub/gitlab_git). The write actions need to be done in a critical path, exclusively for one process. Use an appropriate mutex mechanism to ensure that only one process has write access. Lock-files may be a good option.

**Comment by phyrog** [comment]
[filelock](https://rubygems.org/gems/filelock) might be a good option.

**Comment by eugenk** [comment]
I would place them in `Rails.root.join('tmp/lock')` or `$TMPDIR/lock/ontohub-backend/git/` because these are available on every OS.

Creating the directory of the owner first is no problem at all.
