### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-backend#87]
Add a notion of an admin and set up authorisation. Search for the best library for the job. In legacy-Ontohub, we wanted to switch to [pundit](https://github.com/elabs/pundit) because policies are just ruby objects and they can be used more easily in the [git-shell](https://github.com/ontohub/ontohub-git-shell), which we want to be light-weight.

**Comment by phyrog** [comment]
Depends on ontohub/ontohub-models#71

**Comment by phyrog** [comment]
I created a gem that helps using Pundit with graphql: [phyrog/graphql-pundit](http://github.com/phyrog/graphql-pundit), but not documentation yet.
